# SPDX-License-Identifier: BUSL-1.1

generic-service-chart:
  autoscaling:
    maxReplicas: 70
  applicationImage:
    tag: &appVersion "latest"
  applicationConfiguration:
    development: false
    logger:
      level: info
    cmd/freezer-refrigerant:
      host: api.ice.io
      version: *appVersion
    #CHANGE_ME Application specific configuration.
