# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
tokenomics:
  adoption:
    milestones: 7
    startingBaseMiningRate: 16
    durationBetweenMilestones: 168h
  miningSessionDuration:
    max: 24h
  extraBonuses:
    duration: 24h
  mining-boost:
    levels:
      12.3:
        miningSessionLengthSeconds: 120
        miningRateBonus: 200
        maxT1Referrals: 2
        slashingDisabled: true
      13.3:
        miningSessionLengthSeconds: 180
        miningRateBonus: 300
        maxT1Referrals: 2
        slashingDisabled: false
      14.3:
        miningSessionLengthSeconds: 240
        miningRateBonus: 400
        maxT1Referrals: 4
        slashingDisabled: true
      10.3:
        miningSessionLengthSeconds: 60
        miningRateBonus: 100
        maxT1Referrals: 1
        slashingDisabled: false
miner:
  ethereumDistributionFrequency:
    min: 24h
    max: 672h
  slashingDaysCount: 10