# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: info
cmd/freezer:
  host: localhost:2443
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 2443
    certPath: cmd/freezer/.testdata/localhost.crt
    keyPath: cmd/freezer/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
  wintr/auth/ice:
    jwtSecret: bogus
cmd/freezer-miner:
  host: localhost:5343
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 5343
    certPath: cmd/freezer-refrigerant/.testdata/localhost.crt
    keyPath: cmd/freezer-refrigerant/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
  wintr/auth/ice:
    jwtSecret: bogus
cmd/freezer-refrigerant:
  host: localhost:3443
  version: local
  defaultEndpointTimeout: 30s
  #tenant: sunwaves
  httpServer:
    port: 3443
    certPath: cmd/freezer-refrigerant/.testdata/localhost.crt
    keyPath: cmd/freezer-refrigerant/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
  wintr/auth/ice:
    jwtSecret: bogus
mining-boost: &mining-boost
  priceDelta: 10
  sessionLength: 15m
  levels:
    1.0:
      miningSessionLengthSeconds: 60
      miningRateBonus: 25
      maxT1Referrals: 5
      slashingDisabled: false
    2.0:
      miningSessionLengthSeconds: 60
      miningRateBonus: 50
      maxT1Referrals: 10
      slashingDisabled: false
    3.0:
      miningSessionLengthSeconds: 60
      miningRateBonus: 75
      maxT1Referrals: 15
      slashingDisabled: false
    4.0:
      miningSessionLengthSeconds: 120
      miningRateBonus: 100
      maxT1Referrals: 20
      slashingDisabled: false
    5.0:
      miningSessionLengthSeconds: 120
      miningRateBonus: 125
      maxT1Referrals: 25
      slashingDisabled: true
  contractAddresses:
    ethereum: "0x79F05c263055BA20EE0e814ACD117C20CAA10e0c"
    arbitrum: "0x0b2402144bb366a632d14b83f244d2e0e21bd39c"
    bnb: "0xc335Df7C25b72eEC661d5Aa32a7c2B7b2a1D1874"
  networkEndpoints:
    ethereum:
      - https://ethereum-rpc.publicnode.com
    arbitrum:
      - https://arbitrum.llamarpc.com
    bnb:
      - https://bsc-dataseed1.binance.org/
  paymentAddress: "0x0000000000000000000000000000000000000000"
tokenomics: &tokenomics
  t1ReferralsAllowedWithoutAnyMiningBoostLevel: false
  tasksV2Enabled: false
  adminUsers:
    - user1
    - user2
  welcomeBonusV2Amount: 500
  defaultReferralName: bogus
  slashingFloor: 5
  adoption:
    startingBaseMiningRate: 16
    milestones: 7
    durationBetweenMilestones: 3m
  blockchain-coin-stats-json-url: https://ice-staging.b-cdn.net/sunwaves/assets/blockchain_coin_stats.json
  tenant: generic
  kyc:
    try-reset-kyc-steps-url: https://localhost:1443/v1w/kyc/tryResetKYCSteps/users
    config-json-url: https://ice-staging.b-cdn.net/something/somebogus.json
    face-recognition-delay: 5m
    social1-delay: 3m
    quiz-delay: 3m
    social2-delay: 3m
    social3-delay: 3m
    #    require-quiz-only-on-specific-day-of-week: 1
  bookkeeper/storage: &bookkeeperStorage
    runDDL: true
    urls:
      - localhost:9000
    db: default
    poolSize: 1
    credentials:
      user: default
      password:
  wintr/connectors/storage/v3:
    url: redis://default:@localhost:6381
  wintr/connectors/storage/v2: &globalDB
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5437/freezer-global
    timeout: 90s
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5437/freezer-global
  messageBroker: &tokenomicsMessageBroker
    consumerGroup: freezer-local
    createTopics: true
    urls:
      - localhost:9092
    topics: &tokenomicsMessageBrokerTopics
      - name: freezer-health-check
        partitions: 1
        replicationFactor: 1
        retention: 10s
      - name: adoption-table
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: balances-table
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: available-daily-bonuses
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: started-days-off
        partitions: 10
        replicationFactor: 1
        retention: 10s
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: completed-tasks
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: viewed-news
        partitions: 10
        replicationFactor: 1
        retention: 10s
      - name: user-device-metadata-table
        partitions: 10
        replicationFactor: 1
        retention: 10s
    consumingTopics:
      - name: users-table
      - name: mining-sessions-table
      - name: completed-tasks
      - name: viewed-news
      - name: user-device-metadata-table
  wintr/multimedia/picture:
    urlDownload: https://ice-staging.b-cdn.net/profile
  referralBonusMiningRates:
    t0: 25
    t1: 25
    t2: 5
  t1LimitCount: 2
  rollbackNegativeMining:
    available:
      after: 5m
      until: 60m
  miningSessionDuration:
    min: 30s
    max: 1m
    warnAboutExpirationAfter: 50s
  consecutiveNaturalMiningSessionsRequiredFor1ExtraFreeArtificialMiningSession:
    min: 12
    max: 6
  globalAggregationInterval:
    parent: 60m
    child: 1m
  adoptionMilestoneSwitch:
    duration: 60s
    consecutiveDurationsRequired: 7
    activeUserMilestones:
      - users: 0
        baseMiningRate: 32
      - users: 2
        baseMiningRate: 16
      - users: 4
        baseMiningRate: 8
      - users: 6
        baseMiningRate: 4
      - users: 8
        baseMiningRate: 2
      - users: 10
        baseMiningRate: 1
  extraBonuses:
    duration: 24m
    utcOffsetDuration: 6s
    claimWindow: 1m
    delayedClaimPenaltyWindow: 15s
    availabilityWindow: 10m
    timeToAvailabilityWindow: 10m
    flatValues:
      - 2
      - 4
      - 6
      - 8
      - 10
    newsSeenValues:
      - 0
      - 6
      - 15
      - 54
      - 90
    miningStreakValues:
      - 0
      - 2
      - 5
      - 9
      - 20
    kycPassedExtraBonus: 300
  mining-boost: *mining-boost
  detailed-coin-metrics:
    refresh-interval: 1m
wintr/connectors/storage/v2: &db
  runDDL: true
  primaryURL: postgresql://root:pass@localhost:5437/freezer-global
  credentials:
    user: root
    password: pass
  replicaURLs:
    - postgresql://root:pass@localhost:5437/freezer-global
miner:
  ethereumDistributionFrequency:
    min: 24h
    max: 672h
  bookkeeper/storage: *bookkeeperStorage
  development: true
  workers: 2
  batchSize: 100
  wintr/connectors/storage/v2: *db
  mainnetRewardPoolContributionPercentage: 0.3
  mainnetRewardPoolContributionEthAddress: bogus
  slashingStartInterval: 1m
  slashingDaysCount: 10
  t1LimitCount: 2
  welcomeBonusV2Amount: 500
  t1ReferralsAllowedWithoutAnyMiningBoostLevel: false
kyc/quiz:
  maxResetCount: 0
  maxAttemptsAllowed: 3
  availabilityWindowSeconds: 600
  globalStartDate: '2024-02-03T16:20:52.156534Z'
  wintr/connectors/storage/v2: &usersdb
    runDDL: false
    primaryURL: postgresql://root:pass@localhost:5433/eskimo
    timeout: 90s
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5433/eskimo
coin-distribution:
  alert-slack-webhook: https://hooks.slack.com/services/dummy/dummy/dummy
  environment: local
  review-url: https://some.bogus.example.com/going/somewhere
  development: true
  workers: 2
  batchSize: 100
  wintr/connectors/storage/v2: *db
extra-bonus-notifier:
  workers: 1
  miningSessionDuration: 1m
  batchSize: 100
  chunks: 1000
balance-synchronizer:
  workers: 1
  batchSize: 100
users: &users
  wintr/connectors/storage/v2: &usersdb
    runDDL: false
    primaryURL: postgresql://root:pass@localhost:5433/eskimo
    timeout: 90s
    credentials:
      user: root
      password: pass
    replicaURLs:
      - postgresql://root:pass@localhost:5433/eskimo
tokenomics_test:
  <<: *tokenomics
  messageBroker:
    <<: *tokenomicsMessageBroker
    consumingTopics: *tokenomicsMessageBrokerTopics
    consumerGroup: freezer-local-test