# SPDX-License-Identifier: BUSL-1.1

development: true
logger:
  encoder: console
  level: info
cmd/freezer:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 443
    certPath: cmd/freezer/.testdata/localhost.crt
    keyPath: cmd/freezer/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
cmd/freezer-refrigerant:
  host: localhost
  version: local
  defaultEndpointTimeout: 30s
  httpServer:
    port: 8085
    certPath: cmd/freezer-refrigerant/.testdata/localhost.crt
    keyPath: cmd/freezer-refrigerant/.testdata/localhost.key
  defaultPagination:
    limit: 20
    maxLimit: 1000
economy:
  rates:
    tier0: 25
    tier1: 25
    tier2: 5
  inactivityHoursDeadline: 24
  db:
    spaces:
      - GLOBAL
      - TOTAL_USERS_HISTORY
      - ADOPTION
      - ADOPTION_HISTORY
      - USER_ECONOMY
      - STAKING
      - STAKING_BONUS
      - BALANCES
    urls:
      - localhost:3301
    user: admin
    password: pass
  messageBroker:
    #It's not used, because we`re not consuming anything in the production code.
    #So, its configured here just for testing or other local purposes.
    consumerGroup: freezer-local
    createTopics: true
    urls:
      - localhost:9092
    consumingTopics:
      - users-events
      - balances-update
      - adoption-update
    topics:
      - name: economy-mining
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: economy-staking
        partitions: 10
        replicationFactor: 1
        retention: 1000h
        ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: balances-update
        partitions: 10
        partition: 1
        replicationFactor: 1
        retention: 1000h
        cleanupPolicy: compact
      - name: adoption-update
        partitions: 10
        replicationFactor: 1
        retention: 1000h
        cleanupPolicy: compact
      - name: balances-events
        partitions: 10
        replicationFactor: 1
        retention: 1000h
