# SPDX-License-Identifier: BUSL-1.1

generic-service-chart:
  autoscaling:
    maxReplicas: 21
  applicationImage:
    tag: &appVersion "latest"
  applicationConfiguration:
    development: true
    logger:
      level: debug
    cmd/freezer-refrigerant:
      host: staging.api.ice.io
      version: *appVersion
    #CHANGE_ME Application specific configuration.
