# SPDX-License-Identifier: BUSL-1.1

generic-service-chart:
    applicationService:
        crt: CHANGE_ME
        key: CHANGE_ME
    additionalMounts:
        #CHANGE_ME
    customSecrets:
        #CHANGE_ME
    applicationSecrets:
        #CHANGE_ME