# SPDX-License-Identifier: BUSL-1.1

generic-service-chart:

  fullnameOverride: "freezer-refrigerant"

  resources:
    limits:
      cpu: "1"
      memory: 1.5Gi
    requests:
      cpu: "1"
      memory: 1Gi

  autoscaling:
    enabled: true
    minReplicas: 1
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  applicationService:
    http2: true

  applicationImage:
    pullPolicy: "Always"
    repository: "registry.digitalocean.com/ice-io/freezer-refrigerant"
    imagePullSecrets:
      - registry-credentials

  applicationHealthCheckPath: "/health-check"

  applicationConfigurationMountPoint: "/"

  ingress:
    enabled: true
    annotations:
      external-dns: "yes"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    paths:
      - path: /CHANGE_ME
        pathType: Prefix


  applicationConfiguration:
    logger:
      encoder: console
    cmd/freezer-refrigerant:
      defaultEndpointTimeout: 30s
      httpServer:
        port: 443
        certPath: tls.crt
        keyPath: tls.key
      defaultPagination:
        limit: 20
        maxLimit: 1000
    #Extend the configuration with service specific data.