# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug

tokenomics/detailed-coin-metrics:
#  api-key: <API key to use from https://coinmarketcap.com/api>
