# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
tokenomics: &tokenomics
  wintr/connectors/storage/v2:
    runDDL: true
    primaryURL: postgresql://root:pass@localhost:5432/ice
    replicaURLs:
      - postgresql://root:pass@localhost:5432/ice
  messageBroker: &tokenomicsMessageBroker
    consumerGroup: tokenomics-testing
    createTopics: true
    urls:
      - localhost:9093
    topics: &tokenomicsMessageBrokerTopics
      - name: freezer-health-check
        partitions: 1
        replicationFactor: 1
        retention: 1000h
      - name: adoption-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: mining-sessions-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: mining-rates-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: balances-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: add-balance-commands
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: pre-stakings-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: available-daily-bonuses
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: started-days-off
        partitions: 10
        replicationFactor: 1
        retention: 10s
      ### The next topics are not owned by this service, but are needed to be created for the local/test environment.
      - name: users-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: global-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: viewed-news
        partitions: 10
        replicationFactor: 1
        retention: 1000h
      - name: user-device-metadata-table
        partitions: 10
        replicationFactor: 1
        retention: 1000h
    consumingTopics:
      - name: users-table
      - name: global-table
      - name: mining-sessions-table
      - name: add-balance-commands
      - name: viewed-news
      - name: user-device-metadata-table
  wintr/multimedia/picture:
    urlDownload: https://ice-staging.b-cdn.net/profile
  workerCount: 10
  referralBonusMiningRates:
    t0: 25
    t1: 25
    t2: 5
  rollbackNegativeMining:
    aggressiveDegradationStartsAfter: 3m
    available:
      after: 1m
      until: 10m
  miningSessionDuration:
    min: 1m
    max: 2m
    warnAboutExpirationAfter: 100s
  consecutiveNaturalMiningSessionsRequiredFor1ExtraFreeArtificialMiningSession:
    min: 12
    max: 6
  globalAggregationInterval:
    parent: 60m
    child: 1m
  adoptionMilestoneSwitch:
    duration: 10s
    consecutiveDurationsRequired: 2
    activeUserMilestones:
      - users: 0
        baseMiningRate: 320000000000
      - users: 2
        baseMiningRate: 160000000000
      - users: 4
        baseMiningRate: 80000000000
      - users: 6
        baseMiningRate: 40000000000
      - users: 8
        baseMiningRate: 20000000000
      - users: 10
        baseMiningRate: 10000000000
  extraBonuses:
    duration: 24m
    utcOffsetDuration: 6s
    claimWindow: 1m
    delayedClaimPenaltyWindow: 15s
    availabilityWindow: 10m
    timeToAvailabilityWindow: 10m
    flatValues:
      - 2
      - 4
      - 6
      - 8
      - 10
    newsSeenValues:
      - 0
      - 6
      - 15
      - 54
      - 90
    miningStreakValues:
      - 0
      - 2
      - 5
      - 9
      - 20
tokenomics_test:
  <<: *tokenomics
  messageBroker:
    <<: *tokenomicsMessageBroker
    consumingTopics: *tokenomicsMessageBrokerTopics
