# SPDX-License-Identifier: BUSL-1.1

apiVersion: v2
name: freezer
version: &version "0.1.0"

dependencies:
  - name: generic-service-chart
    version: *version
    repository: https://helm-charts.CHANGE_ME.CHANGE_ME