// SPDX-License-Identifier: BUSL-1.1

// Package api GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "ice",
            "url": "https://ice.io"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/economy/adoption": {
            "get": {
                "description": "Returns the current adoption information.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economy"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/economy.Adoption"
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/economy/estimated-earnings": {
            "get": {
                "description": "Returns estimated earnings based on the provided parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economy"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "if the user that referred you should be active or not",
                        "name": "t0",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of t1 active referrals you desire",
                        "name": "t1",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of t2 active referrals you desire",
                        "name": "t2",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of years you want to enable staking for",
                        "name": "stakingYears",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "the percentage [0..100] of your balance you want to stake",
                        "name": "stakingAllocation",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/economy.EstimatedEarnings"
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/economy/top-miners": {
            "get": {
                "description": "Returns the paginated leaderboard with top miners.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economy"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "a keyword to look for",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max number of elements to return",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "number of elements to skip before starting to fetch data",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/economy.TopMiner"
                            }
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/economy/user-economy/{userId}": {
            "get": {
                "description": "Returns the user's personal economy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economy"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the user",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/economy.UserEconomy"
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "if not found",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/economy/user-stats": {
            "get": {
                "description": "Returns statistics about the user population.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Economy"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003cAdd access token here\u003e",
                        "description": "Insert your access token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "number of days in the past to look for. Defaults to 7.",
                        "name": "lastNoOfDays",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/economy.UserStats"
                        }
                    },
                    "400": {
                        "description": "if validations fail",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "if not authorized",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "if syntax fails",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "504": {
                        "description": "if request times out",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "economy.Adoption": {
            "type": "object",
            "properties": {
                "adoption": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/economy.AdoptionMilestone"
                    }
                },
                "users": {
                    "$ref": "#/definitions/economy.UserCounter"
                }
            }
        },
        "economy.AdoptionMilestone": {
            "type": "object",
            "properties": {
                "achieved": {
                    "type": "boolean",
                    "example": true
                },
                "hourlyMiningRate": {
                    "type": "string",
                    "example": "12.123456789"
                },
                "users": {
                    "$ref": "#/definitions/economy.UserCounter"
                }
            }
        },
        "economy.Balance": {
            "type": "object",
            "properties": {
                "referrals": {
                    "$ref": "#/definitions/economy.ReferralBalance"
                },
                "total": {
                    "type": "number",
                    "example": 232.5
                }
            }
        },
        "economy.DailyUserGrowth": {
            "type": "object",
            "properties": {
                "day": {
                    "type": "integer",
                    "example": 31
                },
                "month": {
                    "type": "integer",
                    "example": 12
                },
                "users": {
                    "$ref": "#/definitions/economy.UserCounter"
                },
                "year": {
                    "type": "integer",
                    "example": 2022
                }
            }
        },
        "economy.EstimatedEarnings": {
            "type": "object",
            "properties": {
                "stakingHourlyMiningRate": {
                    "type": "string",
                    "example": "12.123456789"
                },
                "standardHourlyMiningRate": {
                    "type": "string",
                    "example": "12.123456789"
                }
            }
        },
        "economy.ReferralBalance": {
            "type": "object",
            "properties": {
                "t1": {
                    "type": "number",
                    "example": 232.5
                },
                "t2": {
                    "type": "number",
                    "example": 232.5
                }
            }
        },
        "economy.Staking": {
            "type": "object",
            "properties": {
                "percentage": {
                    "type": "number",
                    "example": 25
                },
                "years": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "economy.TopMiner": {
            "type": "object",
            "properties": {
                "balance": {
                    "type": "string",
                    "example": "12.123456789"
                },
                "profilePictureURL": {
                    "type": "string",
                    "example": "https://somecdn.com/p1.jpg"
                },
                "userId": {
                    "type": "string",
                    "example": "did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2"
                },
                "username": {
                    "type": "string",
                    "example": "jdoe"
                }
            }
        },
        "economy.UserCounter": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "integer",
                    "example": 1000000000
                },
                "total": {
                    "type": "integer",
                    "example": 1000000000
                }
            }
        },
        "economy.UserEconomy": {
            "type": "object",
            "properties": {
                "adoption": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "number"
                    }
                },
                "balance": {
                    "$ref": "#/definitions/economy.Balance"
                },
                "currentTotalUsers": {
                    "type": "integer",
                    "example": 1000000
                },
                "globalRank": {
                    "type": "integer",
                    "example": 1000
                },
                "hourlyMiningRate": {
                    "type": "number",
                    "example": 232.5
                },
                "lastMiningStartedAt": {
                    "type": "string",
                    "example": "2022-01-03T16:20:52.156534Z"
                },
                "staking": {
                    "$ref": "#/definitions/economy.Staking"
                }
            }
        },
        "economy.UserStats": {
            "type": "object",
            "properties": {
                "userGrowth": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/economy.DailyUserGrowth"
                    }
                },
                "users": {
                    "$ref": "#/definitions/economy.UserCounter"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "SOMETHING_NOT_FOUND"
                },
                "error": {
                    "type": "string",
                    "example": "something is missing"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "latest",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{"https"},
	Title:            "Economy API",
	Description:      "API that handles everything related to read-only operations for user's economy.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
