# SPDX-License-Identifier: ice License 1.0

basePath: /v1r
definitions:
  server.ErrorResponse:
    properties:
      code:
        example: SOMETHING_NOT_FOUND
        type: string
      data:
        additionalProperties: {}
        type: object
      error:
        example: something is missing
        type: string
    type: object
  tokenomics.AdoptionSummary:
    properties:
      milestones:
        items:
          properties:
            achievedAt:
              example: "2022-01-03T16:20:52.156534Z"
              type: string
            baseMiningRate:
              example: 1,243.02
              type: string
            milestone:
              example: 1
              type: integer
            totalActiveUsers:
              example: 1
              type: integer
          type: object
        type: array
      totalActiveUsers:
        example: 11
        type: integer
    type: object
  tokenomics.BalanceHistoryBalanceDiff:
    properties:
      amount:
        example: 1,243.02
        type: string
      bonus:
        example: 120
        type: number
      negative:
        example: true
        type: boolean
    type: object
  tokenomics.BalanceHistoryEntry:
    properties:
      balance:
        $ref: '#/definitions/tokenomics.BalanceHistoryBalanceDiff'
      time:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      timeSeries:
        items:
          $ref: '#/definitions/tokenomics.BalanceHistoryEntry'
        type: array
    type: object
  tokenomics.BalanceSummary:
    properties:
      preStaking:
        example: 1,243.02
        type: string
      standard:
        example: 1,243.02
        type: string
      t1:
        example: 1,243.02
        type: string
      t2:
        example: 1,243.02
        type: string
      total:
        example: 1,243.02
        type: string
      totalNoPreStakingBonus:
        example: 1,243.02
        type: string
      totalReferrals:
        example: 1,243.02
        type: string
    type: object
  tokenomics.Miner:
    properties:
      balance:
        example: "12345.6334"
        type: string
      profilePictureUrl:
        example: https://somecdn.com/p1.jpg
        type: string
      userId:
        example: did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2
        type: string
      username:
        example: jdoe
        type: string
    type: object
  tokenomics.MiningRateBonuses:
    properties:
      extra:
        example: 300
        type: number
      preStaking:
        example: 300
        type: number
      t1:
        example: 100
        type: number
      t2:
        example: 200
        type: number
      total:
        example: 300
        type: number
    type: object
  tokenomics.MiningRateSummary-string:
    properties:
      amount:
        example: 1,234,232.001
        type: string
      bonuses:
        $ref: '#/definitions/tokenomics.MiningRateBonuses'
    type: object
  tokenomics.MiningRateType:
    enum:
    - positive
    - negative
    - none
    type: string
    x-enum-varnames:
    - PositiveMiningRateType
    - NegativeMiningRateType
    - NoneMiningRateType
  tokenomics.MiningRates-tokenomics_MiningRateSummary-string:
    properties:
      base:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      positiveTotalNoPreStakingBonus:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      preStaking:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      standard:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      total:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      totalNoPreStakingBonus:
        $ref: '#/definitions/tokenomics.MiningRateSummary-string'
      type:
        $ref: '#/definitions/tokenomics.MiningRateType'
    type: object
  tokenomics.MiningSession:
    properties:
      endedAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      free:
        example: true
        type: boolean
      resettableStartingAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      startedAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      warnAboutExpirationStartingAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
    type: object
  tokenomics.MiningSummary:
    properties:
      availableExtraBonus:
        example: 2
        type: number
      miningRates:
        $ref: '#/definitions/tokenomics.MiningRates-tokenomics_MiningRateSummary-string'
      miningSession:
        $ref: '#/definitions/tokenomics.MiningSession'
      miningStarted:
        example: true
        type: boolean
      miningStreak:
        example: 2
        type: integer
      remainingFreeMiningSessions:
        example: 1
        type: integer
    type: object
  tokenomics.PreStakingSummary:
    properties:
      allocation:
        example: 100
        type: number
      bonus:
        example: 100
        type: number
      years:
        example: 1
        type: integer
    type: object
  tokenomics.RankingSummary:
    properties:
      globalRank:
        example: 12333
        type: integer
    type: object
info:
  contact:
    name: ice.io
    url: https://ice.io
  description: API that handles everything related to read-only operations for user's
    tokenomics and statistics about it.
  title: Tokenomics API
  version: latest
paths:
  /tokenomics-statistics/adoption:
    get:
      consumes:
      - application/json
      description: Returns the current adoption information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenomics.AdoptionSummary'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Statistics
  /tokenomics-statistics/top-miners:
    get:
      consumes:
      - application/json
      description: Returns the paginated leaderboard with top miners.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: a keyword to look for in the user's username or firstname/lastname
        in: query
        name: keyword
        type: string
      - description: max number of elements to return. Default is `10`.
        in: query
        name: limit
        type: integer
      - description: number of elements to skip before starting to fetch data
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          headers:
            X-Next-Offset:
              description: 'if this value is 0, pagination stops, if not, use it in
                the `offset` query param for the next call. '
              type: integer
          schema:
            items:
              $ref: '#/definitions/tokenomics.Miner'
            type: array
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Statistics
  /tokenomics/{userId}/balance-history:
    get:
      consumes:
      - application/json
      description: |-
        Returns the balance history for the provided params.
        If `startDate` is after `endDate`, we go backwards in time: I.E. today, yesterday, etc.
        If `startDate` is before `endDate`, we go forwards in time: I.E. today, tomorrow, etc.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      - description: The start date in RFC3339 or ISO8601 formats. Default is `now`
          in UTC.
        in: query
        name: startDate
        type: string
      - description: The start date in RFC3339 or ISO8601 formats. Default is `end
          of day, relative to startDate`.
        in: query
        name: endDate
        type: string
      - description: The user's timezone. I.E. `+03:00`, `-1:30`. Default is UTC.
        in: query
        name: tz
        type: string
      - description: max number of elements to return. Default is `24`.
        in: query
        name: limit
        type: integer
      - description: number of elements to skip before starting to fetch data
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/tokenomics.BalanceHistoryEntry'
            type: array
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Tokenomics
  /tokenomics/{userId}/balance-summary:
    get:
      consumes:
      - application/json
      description: Returns the balance related information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenomics.BalanceSummary'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Tokenomics
  /tokenomics/{userId}/mining-summary:
    get:
      consumes:
      - application/json
      description: Returns the mining related information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenomics.MiningSummary'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: if not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Tokenomics
  /tokenomics/{userId}/pre-staking-summary:
    get:
      consumes:
      - application/json
      description: Returns the pre-staking related information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenomics.PreStakingSummary'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if not allowed
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: if not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Tokenomics
  /tokenomics/{userId}/ranking-summary:
    get:
      consumes:
      - application/json
      description: Returns the ranking related information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/tokenomics.RankingSummary'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "403":
          description: if hidden by the user
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Tokenomics
schemes:
- https
swagger: "2.0"
