# SPDX-License-Identifier: BUSL-1.1

basePath: /v1
definitions:
  economy.Adoption:
    properties:
      adoption:
        items:
          $ref: '#/definitions/economy.AdoptionMilestone'
        type: array
      users:
        $ref: '#/definitions/economy.UserCounter'
    type: object
  economy.AdoptionMilestone:
    properties:
      achieved:
        example: true
        type: boolean
      hourlyMiningRate:
        example: "12.123456789"
        type: string
      users:
        $ref: '#/definitions/economy.UserCounter'
    type: object
  economy.Balance:
    properties:
      referrals:
        $ref: '#/definitions/economy.ReferralBalance'
      total:
        example: 232.5
        type: number
    type: object
  economy.DailyUserGrowth:
    properties:
      day:
        example: 31
        type: integer
      month:
        example: 12
        type: integer
      users:
        $ref: '#/definitions/economy.UserCounter'
      year:
        example: 2022
        type: integer
    type: object
  economy.EstimatedEarnings:
    properties:
      stakingHourlyMiningRate:
        example: "12.123456789"
        type: string
      standardHourlyMiningRate:
        example: "12.123456789"
        type: string
    type: object
  economy.ReferralBalance:
    properties:
      t1:
        example: 232.5
        type: number
      t2:
        example: 232.5
        type: number
    type: object
  economy.Staking:
    properties:
      percentage:
        example: 25
        type: number
      years:
        example: 1
        type: integer
    type: object
  economy.TopMiner:
    properties:
      balance:
        example: 232.5
        type: number
      profilePictureURL:
        example: https://somecdn.com/p1.jpg
        type: string
      userId:
        example: did:ethr:0x4B73C58370AEfcEf86A6021afCDe5673511376B2
        type: string
      username:
        example: jdoe
        type: string
    type: object
  economy.UserCounter:
    properties:
      active:
        example: 1000000000
        type: integer
      total:
        example: 1000000000
        type: integer
    type: object
  economy.UserEconomy:
    properties:
      adoption:
        additionalProperties:
          type: number
        type: object
      balance:
        $ref: '#/definitions/economy.Balance'
      currentTotalUsers:
        example: 1000000
        type: integer
      globalRank:
        example: 1000
        type: integer
      hourlyMiningRate:
        example: 232.5
        type: number
      lastMiningStartedAt:
        example: "2022-01-03T16:20:52.156534Z"
        type: string
      staking:
        $ref: '#/definitions/economy.Staking'
    type: object
  economy.UserStats:
    properties:
      userGrowth:
        items:
          $ref: '#/definitions/economy.DailyUserGrowth'
        type: array
      users:
        $ref: '#/definitions/economy.UserCounter'
    type: object
  server.ErrorResponse:
    properties:
      code:
        example: SOMETHING_NOT_FOUND
        type: string
      error:
        example: something is missing
        type: string
    type: object
info:
  contact:
    name: ice
    url: https://ice.io
  description: API that handles everything related to read-only operations for user's
    economy.
  title: Economy API
  version: latest
paths:
  /economy/adoption:
    get:
      consumes:
      - application/json
      description: Returns the current adoption information.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/economy.Adoption'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Economy
  /economy/estimated-earnings:
    get:
      consumes:
      - application/json
      description: Returns estimated earnings based on the provided parameters.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: if the user that referred you should be active or not
        in: query
        name: t0
        type: boolean
      - description: number of t1 active referrals you desire
        in: query
        name: t1
        type: integer
      - description: number of t2 active referrals you desire
        in: query
        name: t2
        type: integer
      - description: number of years you want to enable staking for
        in: query
        name: stakingYears
        type: integer
      - description: the percentage [0..100] of your balance you want to stake
        in: query
        name: stakingAllocation
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/economy.EstimatedEarnings'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Economy
  /economy/top-miners:
    get:
      consumes:
      - application/json
      description: Returns the paginated leaderboard with top miners.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: max number of elements to return
        in: query
        name: limit
        type: integer
      - description: number of elements to skip before starting to fetch data
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/economy.TopMiner'
            type: array
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Economy
  /economy/user-economy/{userId}:
    get:
      consumes:
      - application/json
      description: Returns the user's personal economy
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: ID of the user
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/economy.UserEconomy'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "404":
          description: if not found
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Economy
  /economy/user-stats:
    get:
      consumes:
      - application/json
      description: Returns statistics about the user population.
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: number of days in the past to look for. Defaults to 7.
        in: query
        name: lastNoOfDays
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/economy.UserStats'
        "400":
          description: if validations fail
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "401":
          description: if not authorized
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "422":
          description: if syntax fails
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.ErrorResponse'
        "504":
          description: if request times out
          schema:
            $ref: '#/definitions/server.ErrorResponse'
      tags:
      - Economy
schemes:
- https
swagger: "2.0"
