# SPDX-License-Identifier: BUSL-1.1

name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Find latest Go Version
        id: findLatestGoVersion
        run: |
          LATEST_GO_VERSION=$(make latestGoVersion)
          echo "::set-output name=latestGoVersion::$LATEST_GO_VERSION"
      - name: Setup GO
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.findLatestGoVersion.outputs.latestGoVersion }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: Make
        run: make
      - name: Compute new Tag version
        id: compute_tag
        uses: craig-day/compute-tag@v13
        with:
          github_token: ${{ github.token }}
          version_type: minor
      - id: check_tag
        name: Check new computed Tag version
        run: |
          NEW_TAG_VERSION=$(echo "$NEW_TAG_VERSION" | sed 's/.\{2\}$//')
          if [ $NEW_TAG_VERSION == 'v1.0.0' ]
          then
              echo "::set-output name=next_tag::$NEW_TAG_VERSION"
          else
              echo "::set-output name=next_tag::${NEW_TAG_VERSION}.0"
          fi
        env:
          NEW_TAG_VERSION: ${{ steps.compute_tag.outputs.next_tag }}
      - name: Create Release
        id: create_release
        #TODO This needs to be replaced ASAP! https://github.com/actions/create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check_tag.outputs.next_tag }}
          release_name: ${{ steps.check_tag.outputs.next_tag }}
          draft: false
          prerelease: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true
      - name: Login to Digital Ocean Container Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DO_CONTAINER_REGISTRY_TOKEN }}
          password: ${{ secrets.DO_CONTAINER_REGISTRY_TOKEN }}
      - name: Build Image Information
        id: build-image-info
        env:
          VERSION: ${{ steps.check_tag.outputs.next_tag }}
        run: |
          SERVICE_NAME=freezer
          LATEST_TAG=registry.digitalocean.com/ice-io/$SERVICE_NAME:latest
          NEXT_VERSION_TAG=registry.digitalocean.com/ice-io/$SERVICE_NAME:$VERSION
          DOCKERFILE_LOCATION=./cmd/$SERVICE_NAME/Dockerfile
          echo "::set-output name=cmd1Tags::${LATEST_TAG},${NEXT_VERSION_TAG}"
          echo "::set-output name=cmd1DockerFileLocation::$DOCKERFILE_LOCATION"
          SERVICE_NAME=freezer-refrigerator
          LATEST_TAG=registry.digitalocean.com/ice-io/$SERVICE_NAME:latest
          NEXT_VERSION_TAG=registry.digitalocean.com/ice-io/$SERVICE_NAME:$VERSION
          DOCKERFILE_LOCATION=./cmd/$SERVICE_NAME/Dockerfile
          echo "::set-output name=cmd2Tags::${LATEST_TAG},${NEXT_VERSION_TAG}"
          echo "::set-output name=cmd2DockerFileLocation::$DOCKERFILE_LOCATION"
      - name: Build Freezer Image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.build-image-info.outputs.cmd1DockerFileLocation }}
          #those are not supported by golang docker image: linux/riscv64
          #platforms: linux/s390x,linux/arm64,linux/amd64,linux/ppc64le
          #commented because build takes too damn much with the other 3 platforms (~10 mins for each!!!) and we don`t need them atm
          platforms: linux/amd64
          push: true
          build-args: |
            SERVICE_NAME=freezer
          tags: ${{ steps.build-image-info.outputs.cmd1Tags }}
      - name: Build Freezer Refrigerant Image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ steps.build-image-info.outputs.cmd2DockerFileLocation }}
          #those are not supported by golang docker image: linux/riscv64
          #platforms: linux/s390x,linux/arm64,linux/amd64,linux/ppc64le
          #commented because build takes too damn much with the other 3 platforms (~10 mins for each!!!) and we don`t need them atm
          platforms: linux/amd64
          push: true
          build-args: |
            SERVICE_NAME=freezer-refrigerant
          tags: ${{ steps.build-image-info.outputs.cmd2Tags }}
      - name: Setting ENV variables for deployment
        run: |
          echo "APP_TAG=${{steps.check_tag.outputs.next_tag}}" >> $GITHUB_ENV
      - name: Checkout the target `deploy` branch of `secret-infrastructure`
        uses: actions/checkout@v3
        with:
          repository: ice-blockchain/secret-infrastructure
          ref: deploy
          token: ${{ secrets.ICE_CI_CD_BOT_GH_PAT }}
          path: secret-infrastructure
          fetch-depth: 0
      - name: Rebase to secret-infrastructure master
        run: git rebase origin/master
      - name: Update [staging] application tag version in .deploy/helm/freezer-refrigerator/staging/common-values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' .deploy/helm/freezer-refrigerator/staging/common-values.yaml
      - name: Update [production] application tag version in .deploy/helm/freezer-refrigerator/production/common-values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' .deploy/helm/freezer-refrigerator/production/common-values.yaml
      - name: Update [staging] application tag version in .deploy/helm/freezer/staging/common-values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' .deploy/helm/freezer/staging/common-values.yaml
      - name: Update [production] application tag version in .deploy/helm/freezer/production/common-values.yaml
        uses: mikefarah/yq@master
        with:
          cmd: yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' .deploy/helm/freezer/production/common-values.yaml
      - name: Commit and Push Changes to Application Tag Version
        run: |
          git config user.name "ICE CI/CD Bot"
          git config user.email ice-cicd-bot@ice.vip
          git status
          git add .deploy/helm/freezer-refrigerant/staging/common-values.yaml 
          git add .deploy/helm/freezer-refrigerant/production/common-values.yaml
          git add .deploy/helm/freezer/staging/common-values.yaml 
          git add .deploy/helm/freezer/production/common-values.yaml
          git commit -m "Updated `freezer` & `freezer-refrigerant` tag version (${{env.APP_TAG}}) in application helm chart deployment manifests"
          git push --set-upstream origin deploy
      - name: Slack Notification For Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.BACKEND_SLACK_WEBHOOK }}
          SLACK_TITLE: CI Succeeded, Waiting for Deployment Status Notification...
          SLACK_USERNAME: ${{ github.event.repository.name }}-ci-bot
          SLACK_ICON: https://avatars.githubusercontent.com/u/102382658?s=400&u=62e73f4cb845c48a07a19e03c6f84b721e40c0a6&v=4
          SLACK_ICON_EMOJI: ':rocket:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ${{ github.event.repository.name }} >> TODO replace this with API URL
      - name: Slack Notification For Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.BACKEND_SLACK_WEBHOOK }}
          SLACK_TITLE: CI Failed
          SLACK_USERNAME: ${{ github.event.repository.name }}-ci-bot
          SLACK_ICON: https://avatars.githubusercontent.com/u/102382658?s=400&u=62e73f4cb845c48a07a19e03c6f84b721e40c0a6&v=4
          SLACK_ICON_EMOJI: ':sob:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ${{ github.event.repository.name }} >> TODO replace this with API URL
      - name: Slack Notification For Cancellation
        if: ${{ cancelled() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.BACKEND_SLACK_WEBHOOK }}
          SLACK_TITLE: CI Cancelled
          SLACK_USERNAME: ${{ github.event.repository.name }}-ci-bot
          SLACK_ICON: https://avatars.githubusercontent.com/u/102382658?s=400&u=62e73f4cb845c48a07a19e03c6f84b721e40c0a6&v=4
          SLACK_ICON_EMOJI: ':X:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_FOOTER: ${{ github.event.repository.name }} >> TODO replace this with API URL
